### ISSUE TITLE
Demo running on colab

### ISSUE THREAD

**Issue by Kogam22** [facebookresearch/swav#10]
So I was trying to get this working as a prototype on google colab. I installed apex, and when I run 
```bash
python -m torch.distributed.launch main_swav.py \
--data_path /content/data/fer/images \
--epochs  20 \
--base_lr 0.6 \
--final_lr 0.0006 \
--warmup_epochs 0 \
--batch_size 32 \
--size_crops 48 48 \
--use_fp16 true \
--freeze_prototypes_niters 5005 \
--queue_length 0 \
--epoch_queue_starts 15
```

I get this error : 
```bash
Traceback (most recent call last):
  File "main_swav.py", line 375, in <module>
    main()
  File "main_swav.py", line 123, in main
    init_distributed_mode(args)
  File "/content/swav/src/utils.py", line 65, in init_distributed_mode
    rank=args.rank,
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 391, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rendezvous.py", line 79, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for ://
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'main_swav.py', '--local_rank=0', '--data_path', '/content/data/fer/images', '--epochs', '20', '--base_lr', '0.6', '--final_lr', '0.0006', '--warmup_epochs', '0', '--batch_size', '32', '--size_crops', '48', '48', '--use_fp16', 'true', '--freeze_prototypes_niters', '5005', '--queue_length', '0', '--epoch_queue_starts', '15']' returned non-zero exit status 1.
```

Thinking this might be related to the `python -m torch.distributed.launch \` because obviously I am not using a distributed computing environment, I try to change it to maybe `torch.launch` which does not obviously work.

Can I get any help ? Thanks.

**Comment by Kogam22** [comment]
The dataset I was trying to use is FER2013 dataset. All training + testing dataset gives around 37k 48x48 images.

**Comment by mathildecaron31** [comment]
Hi, even when running the code with 1 gpu you need to specify an init method with the flag `--dist_url`. See https://github.com/facebookresearch/swav/issues/2

**Comment by mathildecaron31** [comment]
I've made a valid default for the --dist_url parameter:
139623b23be7d1f0caeea7aa5fb292f811df22d7
