### ISSUE TITLE
RuntimeError: No rendezvous handler for ://

### ISSUE THREAD

**Issue by heesubsong** [facebookresearch/swav#2]
Hello

I am trying to train a custom dataset.

I am trying to train in an environment where there is one gpu.

What's the problem?

Also, can you provide a tutorial for testing on a custom dataset?

export NGPU=1; python -m torch.distributed.launch --nproc_per_node=$NGPU main_swav.py --data_path /home/ubuntu/merge/src/swav/data/train --epochs 400 --base_lr 0.6 --final_lr 0.0006 --warmup_epochs 0 --batch_size 32 --size_crops 224 96 --nmb_crops 2 6 --min_scale_crops 0.14 0.05 --max_scale_crops 1. 0.14 --use_fp16 true --freeze_prototypes_niters 5005 --queue_length 3840 --epoch_queue_starts 15
Traceback (most recent call last):
  File "main_swav.py", line 374, in <module>
    main()
  File "main_swav.py", line 122, in main
    init_distributed_mode(args)
  File "/home/ubuntu/merge/src/swav/src/utils.py", line 65, in init_distributed_mode
    rank=args.rank,
  File "/home/ubuntu/anaconda3/envs/swav/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 391, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "/home/ubuntu/anaconda3/envs/swav/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 79, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for ://
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/swav/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/swav/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/swav/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/swav/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/swav/bin/python', '-u', 'main_swav.py', '--local_rank=0', '--data_path', '/home/ubuntu/merge/src/swav/data/train', '--epochs', '400', '--base_lr', '0.6', '--final_lr', '0.0006', '--warmup_epochs', '0', '--batch_size', '32', '--size_crops', '224', '96', '--nmb_crops', '2', '6', '--min_scale_crops', '0.14', '0.05', '--max_scale_crops', '1.', '0.14', '--use_fp16', 'true', '--freeze_prototypes_niters', '5005', '--queue_length', '3840', '--epoch_queue_starts', '15']' returned non-zero exit status 1.

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest
Even when training on 1 gpu you should set up the `--dist_url` flag ! You can use [env](https://pytorch.org/docs/stable/distributed.html#environment-variable-initialization) or [file](https://pytorch.org/docs/stable/distributed.html#shared-file-system-initialization) or [tcp](https://pytorch.org/docs/stable/distributed.html#tcp-initialization) init methods.

For example you could specify `--dist_url file:///path/to/your/home/sharedfile`

**Comment by mathildecaron31** [comment]
I've made a valid default for the --dist_url parameter:
139623b23be7d1f0caeea7aa5fb292f811df22d7
