### ISSUE TITLE
Non-distributed training

### ISSUE THREAD

**Issue by Youngboy12** [facebookresearch/swav#33]
If I run main_deepclusterv2.py in a non-distributed training mode, what modifications do I need to make？

Traceback (most recent call last):
  File "main_deepclusterv2.py", line 426, in <module>
    main()
  File "main_deepclusterv2.py", line 119, in main
    init_distributed_mode(args)
  File "/remote_projects/ImageSimilarity/swav/src/utils.py", line 56, in init_distributed_mode
    args.rank = int(os.environ["RANK"])
  File "/root/software/anaconda3/envs/similarity/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by mathildecaron31** [comment]
Hi @Youngboy12 .

I fyou want to run the code with only 1 GPU (hence non-distributed mode) you can launch the following:
`python -m torch.distributed.launch --nproc_per_node=1 main_deepclusterv2.py`

**Comment by Youngboy12** [comment]
OK，Thank you
